linux_docker_builder:    
  env:
    DOCKERHUB_USER: ENCRYPTED[ccd1af2835558f6b3e08fa3dd8ad95e7b3eaf3b83220433093d6335a3f4727f4c53c4053587d1594799e72e331d1017d]
    DOCKERHUB_PASS: ENCRYPTED[7b81d2ca7878761ea497619cae892e267c0e0fdee71d8ce48dcd4ba11b9351a9d3f2f781dce84a7f8aab92a278007509]
  script: |
    docker build -t $CIRRUS_REPO_FULL_NAME:cirrus-linux . -f Dockerfile
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker push $CIRRUS_REPO_FULL_NAME:cirrus-linux

linuxarmv7_docker_builder:    
  env:
    DOCKERHUB_USER: ENCRYPTED[ccd1af2835558f6b3e08fa3dd8ad95e7b3eaf3b83220433093d6335a3f4727f4c53c4053587d1594799e72e331d1017d]
    DOCKERHUB_PASS: ENCRYPTED[7b81d2ca7878761ea497619cae892e267c0e0fdee71d8ce48dcd4ba11b9351a9d3f2f781dce84a7f8aab92a278007509]
  script: |
    docker build -t $CIRRUS_REPO_FULL_NAME:cirrus-armv7 . -f Dockerfile.rpi --build-arg ARCH=armv7l --build-arg CROSSCOMPILER=https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Raspberry%20Pi%20GCC%20Cross-Compiler%20Toolchains/GCC%209.1.0/Raspberry%20Pi%202%2C%203/cross-gcc-9.1.0-pi_2-3.tar.gz --build-arg IMAGE=balenalib/raspberry-pi2
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker push $CIRRUS_REPO_FULL_NAME:cirrus-armv7

linuxarmv6_docker_builder:    
  env:
    DOCKERHUB_USER: ENCRYPTED[ccd1af2835558f6b3e08fa3dd8ad95e7b3eaf3b83220433093d6335a3f4727f4c53c4053587d1594799e72e331d1017d]
    DOCKERHUB_PASS: ENCRYPTED[7b81d2ca7878761ea497619cae892e267c0e0fdee71d8ce48dcd4ba11b9351a9d3f2f781dce84a7f8aab92a278007509]
  script: |
    docker build -t $CIRRUS_REPO_FULL_NAME:cirrus-armv6 . -f Dockerfile.rpi 
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker push $CIRRUS_REPO_FULL_NAME:cirrus-armv6

windows_docker_builder:    
  timeout_in: 120m
  platform: windows
  os_version: 2019  
  env:
    DOCKERHUB_USER: ENCRYPTED[ccd1af2835558f6b3e08fa3dd8ad95e7b3eaf3b83220433093d6335a3f4727f4c53c4053587d1594799e72e331d1017d]
    DOCKERHUB_PASS: ENCRYPTED[7b81d2ca7878761ea497619cae892e267c0e0fdee71d8ce48dcd4ba11b9351a9d3f2f781dce84a7f8aab92a278007509]
  script: |
    docker info
    docker build --rm=false -t %CIRRUS_REPO_FULL_NAME%:cirrus-windows . -f Dockerfile.windows
    docker login --username=%DOCKERHUB_USER% --password=%DOCKERHUB_PASS% 
    docker push %CIRRUS_REPO_FULL_NAME%:windows   
    
publish_docker_builder:
  depends_on: 
    - linuxarmv6
    - linuxarmv7
    - linux
    - windows
  env:
    DOCKER_CLI_EXPERIMENTAL: enabled
    DOCKERHUB_USER: ENCRYPTED[ccd1af2835558f6b3e08fa3dd8ad95e7b3eaf3b83220433093d6335a3f4727f4c53c4053587d1594799e72e331d1017d]
    DOCKERHUB_PASS: ENCRYPTED[7b81d2ca7878761ea497619cae892e267c0e0fdee71d8ce48dcd4ba11b9351a9d3f2f781dce84a7f8aab92a278007509]
  script: | 
    docker info
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker manifest create --amend $CIRRUS_REPO_FULL_NAME:cirrus-latest $CIRRUS_REPO_FULL_NAME:cirrus-linux  $CIRRUS_REPO_FULL_NAME:cirrus-armv6  $CIRRUS_REPO_FULL_NAME:cirrus-windows
    docker manifest push $CIRRUS_REPO_FULL_NAME:cirrus-latest -p
