FROM heroku/heroku:18
ENV WEBRTCROOT /webrtc
ENV GNARGSCOMMON 'rtc_include_tests=false rtc_enable_protobuf=false use_custom_libcxx=false rtc_include_pulse_audio=false rtc_build_examples=false is_clang=false treat_warnings_as_errors=false'
ENV TAR_OPTIONS --no-same-owner
ENV GYP_GENERATOR_OUTPUT "x86_64"
ENV GNARGS 'is_debug=false rtc_use_h264=true ffmpeg_branding="Chrome" use_sysroot=false'
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get update; apt-get install -y --no-install-recommends autoconf automake libtool git make g++ xz-utils nodejs awscli libvncserver-dev pkg-config  libgtk-3-dev libasound2-dev
RUN git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git /depot_tools
ENV PATH=/depot_tools:$PATH
RUN mkdir ${WEBRTCROOT} && cd ${WEBRTCROOT} && fetch --no-history --nohooks webrtc
RUN cd ${WEBRTCROOT} && sed -i -e "s|'src/resources'],|'src/resources'],'condition':'rtc_include_tests==true',|" src/DEPS
RUN cd ${WEBRTCROOT} && gclient sync
RUN cd ${WEBRTCROOT}/src && gn gen ${GYP_GENERATOR_OUTPUT}/out/Release --args="${GNARGSCOMMON} ${GNARGS}"
RUN cd ${WEBRTCROOT}/src && ( ninja -C ${GYP_GENERATOR_OUTPUT}/out/Release jsoncpp rtc_json webrtc builtin_audio_decoder_factory || ninja -C ${GYP_GENERATOR_OUTPUT}/out/Release jsoncpp rtc_json webrtc builtin_audio_decoder_factory || ninja -C ${GYP_GENERATOR_OUTPUT}/out/Release jsoncpp rtc_json webrtc builtin_audio_decoder_factory)
COPY . /webrtc-streamer
WORKDIR /webrtc-streamer
RUN  make live555
RUN make all tgz
