name: Node.js Package

on: [push]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: |
              git submodule update --init
              git fetch --prune --unshallow --tags
      - uses: actions/setup-node@v7
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false  
      - run: npm install
      - run: |
              npm config set git-tag-version=false
              npm config ls -l
              cat $(npm config get userconfig)
              npm version $(git describe --tags --always)
              
      - name: Publish to npm tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
              npm publish --access public

      - name: Publish to npm latest
        if: startsWith(github.ref, 'refs/tags/') == false        
        run: |
              npm publish --tag latest --access public
